resources:
  - ../../base
namespace: nayuta-dev
namePrefix: nayuta-dev-
commonLabels:
  app: nayuta-dev
replicas:
  - name: nayuta-dev-nginx
    count: 7
images:
  - name: nginx
    newName: nginx
    newTag: 1.21-alpine
patchesStrategicMerge:
  - deployment.yaml
